### ISSUE TITLE
Invalid Index When Running EIP-2333 Test Cases in Key Derivation

### ISSUE THREAD

**Issue by rauljordan** [wealdtech/go-eth2-util#2]
Hi @mcdee, line https://github.com/wealdtech/go-eth2-util/blob/5c60bedc90cae473a3baa8484f73ae416f5522f3/crypto.go#L68 throws an error when running EIP conformity tests with a child index such as `3141592653` in [test case 1](https://eips.ethereum.org/EIPS/eip-2333#test-cases)

**Comment by mcdee** [comment]
Great catch, sorry about that.  I'll update the code (should be `ParseUint`) and will roll out updates to this and the modules that include it ASAP.
